FROM alpine:latest

LABEL author="Ashu" maintainer="Matheusn.biolowons@gmail.com"

RUN apk add --update --no-cache \
  ca-certificates \
  curl \
  wget \
  unzip \
  tar \
  git \
  jq \
  file \
  bash