name: build emulation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - emulation/**
jobs:
  push:
    name: "emulation:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - box64
          - box86
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all git history
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./emulation/${{ matrix.tag }}
          file: ./emulation/${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/ashu11-a/emulation:${{ matrix.tag }}

