name: build samp
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - games/samp/**
jobs:
  push:
    name: "games:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - samp
          
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: ./games/${{ matrix.game }}/AMD64
          file: ./games/${{ matrix.game }}/AMD64/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ashu11-a/games:${{ matrix.game }}-amd64

      - uses: docker/build-push-action@v4
        with:
          context: ./games/${{ matrix.game }}/ARM64
          file: ./games/${{ matrix.game }}/ARM64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/ashu11-a/games:${{ matrix.game }}-arm64