name: build software
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - software/**
jobs:
  push:
    name: "software:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - emby
          - jellyfin
          - nextcloud
          - owncloud
          - paneldactyl
          - proot
          - stress
          - python
          - ffmpeg
          - handbrake
          - youtube_dl
          - ass
          - bot4all
          - uguu
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all git history
      - name: Determine if Dockerfile changed
        id: dockerfile-changed
        run: |
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) == *${{ matrix.tag }}* ]]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: steps.dockerfile-changed.outputs.changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: ./software/${{ matrix.tag }}
          file: ./software/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ashu11-a/software:${{ matrix.tag }}
