name: build software
on:
  push:
    branches:
      - main
    paths:
      - software/**
jobs:
  build:
    name: "software:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - emby
          - jellyfin
          - nextcloud
          - owncloud
          - paneldactyl
          - proot
          - stress
          - wings
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Find Dockerfile Changes
        id: find_dockerfile_changes
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD)
          dockerfiles=$(echo "$changed_files" | grep "^software/.*/Dockerfile$")
          echo "::set-env name=dockerfile_path::$dockerfiles"
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.dockerfile_path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ashu11-a/software:${{ matrix.tag }}
