name: build software
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - software/**
jobs:
  push:
    name: "software:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - emby
          - jellyfin
          - nextcloud
          - owncloud
          - paneldactyl
          - proot
          - stress
          - python
          - ffmpeg
          - handbrake
          - youtube_dl
          - bot4all
          - uguu
          - ctrlpanel
          - phpmyadmin
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all git history
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./software/${{ matrix.tag }}
          file: ./software/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ashu11-a/software:${{ matrix.tag }}
